apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-detector
  template:
    metadata:
      labels:
        app: fraud-detector
    spec:
      containers:
      - name: fraud-detector
        image: us-central1-docker.pkg.dev/gothic-welder-398814/tf-serving/fraud-detection:1.0.1
        ports:
        - containerPort: 8501
        env:
        - name: MODEL_NAME
          value: fraud_classifier
        - name: model_base_path
          value: /models/fraud_classifier
